// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5T2XYrbsFXjp2K-wfXz7K7m-wHK-cQp8',
    appId: '1:1003948389961:web:e04c20f7e8843a62f03198',
    messagingSenderId: '1003948389961',
    projectId: 'nodenoty-c9cbc',
    authDomain: 'nodenoty-c9cbc.firebaseapp.com',
    storageBucket: 'nodenoty-c9cbc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB18VIyV8uWb07sQF70DmSOeTv3htg2M5Q',
    appId: '1:1003948389961:android:c2e84d94c7c28acef03198',
    messagingSenderId: '1003948389961',
    projectId: 'nodenoty-c9cbc',
    storageBucket: 'nodenoty-c9cbc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiFBzaGV4M0Dch7sYgAYUPc75EWPQimqY',
    appId: '1:1003948389961:ios:76b23922613d05b0f03198',
    messagingSenderId: '1003948389961',
    projectId: 'nodenoty-c9cbc',
    storageBucket: 'nodenoty-c9cbc.appspot.com',
    iosBundleId: 'com.example.nodenoty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiFBzaGV4M0Dch7sYgAYUPc75EWPQimqY',
    appId: '1:1003948389961:ios:76b23922613d05b0f03198',
    messagingSenderId: '1003948389961',
    projectId: 'nodenoty-c9cbc',
    storageBucket: 'nodenoty-c9cbc.appspot.com',
    iosBundleId: 'com.example.nodenoty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5T2XYrbsFXjp2K-wfXz7K7m-wHK-cQp8',
    appId: '1:1003948389961:web:2bd9e9e94e72ece5f03198',
    messagingSenderId: '1003948389961',
    projectId: 'nodenoty-c9cbc',
    authDomain: 'nodenoty-c9cbc.firebaseapp.com',
    storageBucket: 'nodenoty-c9cbc.appspot.com',
  );
}
